"""record that a claim was rejected

A rejected claim returns the instance to UNTOUCHED, which is the right state:
it stays provisional until settlement, so the child can still do the chore.
But nothing survived to say the rejection happened, which made a refused claim
look exactly like a tap that never registered — and made three refusals
indistinguishable from never having claimed at all.

Neither column changes a rule. They exist so the week view can say "not
accepted, have another go" rather than silently losing the claim. The CHECKs
are added by hand: Alembic does not compare CHECK constraints on SQLite.

Revision ID: 7a0c95a307e0
Revises: e42da40283c5
Create Date: 2026-08-20 18:33:27.953744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.base  # custom column types used by the models


# revision identifiers, used by Alembic.
revision: str = '7a0c95a307e0'
down_revision: Union[str, None] = 'e42da40283c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejected_at', app.models.base.UtcDateTime(), nullable=True))
        batch_op.add_column(sa.Column('rejection_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_check_constraint(
            'ck_chore_instances_rejection_count_not_negative',
            'rejection_count >= 0',
        )
        batch_op.create_check_constraint(
            'ck_chore_instances_a_rejection_records_when_it_happened',
            "(rejection_count = 0 AND rejected_at IS NULL)"
            " OR (rejection_count > 0 AND rejected_at IS NOT NULL)",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore_instances', schema=None) as batch_op:
        batch_op.drop_constraint(
            'ck_chore_instances_a_rejection_records_when_it_happened', type_='check'
        )
        batch_op.drop_constraint(
            'ck_chore_instances_rejection_count_not_negative', type_='check'
        )
        batch_op.drop_column('rejection_count')
        batch_op.drop_column('rejected_at')

    # ### end Alembic commands ###
