"""record how a miss arose

A parent marking a chore missed is a decision: definite the moment it is made,
and it names who made it. A miss established at settlement is the absence of
anything having happened — nobody decided it, so nobody may be recorded as its
author. Storing both as "missed" with a person's name attached would make the
second one say something untrue.

The CHECKs are written by hand; Alembic does not compare CHECK constraints on
SQLite.

Revision ID: 82826e03b64d
Revises: 7a0c95a307e0
Create Date: 2026-08-20 18:43:25.786687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.base  # custom column types used by the models


# revision identifiers, used by Alembic.
revision: str = '82826e03b64d'
down_revision: Union[str, None] = '7a0c95a307e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('miss_origin', sa.Enum('parent_marked', 'inferred_at_settlement', name='ck_missorigin', native_enum=False, length=32), nullable=True))
        batch_op.create_check_constraint(
            'ck_chore_instances_a_miss_says_how_it_arose',
            "(state = 'missed') = (miss_origin IS NOT NULL)",
        )
        batch_op.create_check_constraint(
            'ck_chore_instances_an_inferred_miss_has_no_author',
            "miss_origin <> 'inferred_at_settlement' OR authorised_by IS NULL",
        )
        batch_op.create_check_constraint(
            'ck_chore_instances_a_parent_marked_miss_names_the_parent',
            "miss_origin <> 'parent_marked' OR authorised_by IS NOT NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore_instances', schema=None) as batch_op:
        for name in (
            'ck_chore_instances_a_parent_marked_miss_names_the_parent',
            'ck_chore_instances_an_inferred_miss_has_no_author',
            'ck_chore_instances_a_miss_says_how_it_arose',
        ):
            batch_op.drop_constraint(name, type_='check')
        batch_op.drop_column('miss_origin')

    # ### end Alembic commands ###
