"""weekly-count instances get a sequence

The first revision allowed one week-scoped instance per chore per week, which
is right for a week-long condition and wrong for a chore due three times a
week: those are three separately claimable occasions, not one row with a
quantity nobody can point at. Numbering the slots 1..n restores uniqueness
without collapsing them.

Revision ID: b743007f1216
Revises: 90dcc46188e0
Create Date: 2026-08-20 18:04:20.973183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.base  # custom column types used by the models


# revision identifiers, used by Alembic.
revision: str = 'b743007f1216'
down_revision: Union[str, None] = '90dcc46188e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sequence', sa.Integer(), server_default='1', nullable=False))
        batch_op.drop_index('uq_chore_instances_definition_week', sqlite_where=sa.text('due_date IS NULL'))
        batch_op.create_index('uq_chore_instances_definition_week_sequence', ['definition_id', 'week_id', 'sequence'], unique=True, sqlite_where=sa.text('due_date IS NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore_instances', schema=None) as batch_op:
        batch_op.drop_index('uq_chore_instances_definition_week_sequence', sqlite_where=sa.text('due_date IS NULL'))
        batch_op.create_index('uq_chore_instances_definition_week', ['definition_id', 'week_id'], unique=1, sqlite_where=sa.text('due_date IS NULL'))
        batch_op.drop_column('sequence')

    # ### end Alembic commands ###
