"""record who authorised an instance

There is one parent today, so the column always holds the same string. It is
recorded anyway: when a second parent is authorised alongside the first, the
history will already say which of them agreed what, rather than starting that
record from the day the feature arrives.

The CHECK is added by hand — Alembic's autogenerate does not compare CHECK
constraints on SQLite.

Revision ID: e42da40283c5
Revises: b743007f1216
Create Date: 2026-08-20 18:19:31.712072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.base  # custom column types used by the models


# revision identifiers, used by Alembic.
revision: str = 'e42da40283c5'
down_revision: Union[str, None] = 'b743007f1216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authorised_by', sa.String(length=60), nullable=True))
        batch_op.create_check_constraint(
            'ck_chore_instances_a_confirmation_names_its_author',
            "state <> 'confirmed' OR authorised_by IS NOT NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore_instances', schema=None) as batch_op:
        batch_op.drop_constraint(
            'ck_chore_instances_a_confirmation_names_its_author', type_='check'
        )
        batch_op.drop_column('authorised_by')

    # ### end Alembic commands ###
